name: PR Links

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build site
        uses: iciaran/astro-action@15aa0a5a1e067940253e3b259413ab2ae882a740 # v5.2.0

        with:
          path: "astro" # TODO: change when Astro site is moved to root
          package-manager: npm@latest
          node-version: 24.13